ALTER TABLE roles 
ADD COLUMN IF NOT EXISTS can_cancel_order BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS can_delete_order_item BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS can_decrement_order_item BOOLEAN DEFAULT TRUE;
